//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class BilledTime
    {
        public int BilledTimeID { get; set; }
        public int ProjectCodeID { get; set; }
        public int ProjectSubCodeID { get; set; }
        public System.DateTime BilledDate { get; set; }
        public double BilledHours { get; set; }
        public string Notes { get; set; }
    
        public virtual ProjectCode ProjectCode { get; set; }
        public virtual ProjectSubCode ProjectSubCode { get; set; }
    }
}
