//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalEntity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PersonalEntities : DbContext
    {
        public PersonalEntities()
            : base("name=PersonalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PhoneList> PhoneLists { get; set; }
        public virtual DbSet<ProjectCode> ProjectCodes { get; set; }
        public virtual DbSet<ProjectSubCode> ProjectSubCodes { get; set; }
        public virtual DbSet<BilledTime> BilledTimes { get; set; }
        public virtual DbSet<ProgramMessage> ProgramMessages { get; set; }
        public virtual DbSet<ProgramMessageException> ProgramMessageExceptions { get; set; }
        public virtual DbSet<Holiday> Holidays { get; set; }
        public virtual DbSet<Leave> Leaves { get; set; }
        public virtual DbSet<LeaveType> LeaveTypes { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TagValue> TagValues { get; set; }
        public virtual DbSet<TagType> TagTypes { get; set; }
        public virtual DbSet<Workflow> Workflows { get; set; }
        public virtual DbSet<WorkflowBug> WorkflowBugs { get; set; }
        public virtual DbSet<WorkflowNote> WorkflowNotes { get; set; }
        public virtual DbSet<WorkflowStep> WorkflowSteps { get; set; }
        public virtual DbSet<WorkflowStepState> WorkflowStepStates { get; set; }
    }
}
