//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProgramMessageException
    {
        public int ProgramMessageExceptionID { get; set; }
        public int ProgramMessageID { get; set; }
        public string ExceptionMessage { get; set; }
        public int ExceptionOrder { get; set; }
    
        public virtual ProgramMessage ProgramMessage { get; set; }
    }
}
