//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectSubCode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectSubCode()
        {
            this.Codes = new HashSet<ProjectCode>();
            this.BilledTimes = new HashSet<BilledTime>();
        }
    
        public int ProjectSubCodeID { get; set; }
        public string ProjectSubCodeValue { get; set; }
        public string ProjectSubCodeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectCode> Codes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BilledTime> BilledTimes { get; set; }
    }
}
