//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PersonalEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkflowStep()
        {
            this.Notes = new HashSet<WorkflowNote>();
        }
    
        public int WorkflowStepID { get; set; }
        public int WorkflowID { get; set; }
        public int WorkflowStepStateID { get; set; }
        public Nullable<int> WorkflowBugID { get; set; }
        public string StepDescription { get; set; }
    
        public virtual Workflow Workflow { get; set; }
        public virtual WorkflowBug Bug { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkflowNote> Notes { get; set; }
        public virtual WorkflowStepState StepState { get; set; }
    }
}
